/// replay/recorder.rs — MCAP session recorder
///
/// Writes sensor frames and control metrics to an MCAP file that Foxglove
/// Studio opens natively. Receives all data through a TelemetryEvent channel
/// rather than holding its own mpsc sender, because the TelemetryBus owns
/// the channel lifetime — the recorder is just one subscriber among several.
/// This means the recorder never needs to know about other consumers, and
/// adding a new consumer never requires touching this file.
///
/// Channel layout
/// ──────────────
///   /imu          car_software.ImuSample       (Protobuf, 500 Hz)
///   /lidar        foxglove.PointCloud          (Protobuf, ~10 Hz)
///   /sonar        car_software.SonarFrame      (Protobuf, ~33 Hz)
///   /metrics      car_software.TickMetrics     (Protobuf, 100 Hz)
///   /control      car_software.ControlFrame    (Protobuf, 100 Hz)
use std::{fs::File, io::BufWriter, path::Path, sync::mpsc, thread, time::Instant};

use anyhow::{Context, Result};
use tracing::{info, warn};

use mcap::{records::MessageHeader, Writer};
use prost::Message;

use crate::hal::TimestampedFrame;
use crate::metrics::TickMetrics;
use crate::telemetry::TelemetryEvent;

// ── Generated Protobuf Modules ─────────────────────────────────────────────

pub mod pb_fg {
    include!(concat!(env!("OUT_DIR"), "/foxglove.rs"));
}
pub mod pb_car {
    include!(concat!(env!("OUT_DIR"), "/car_software.rs"));
}

// ── Public Types ───────────────────────────────────────────────────────────

/// Actuator commands recorded alongside sensor data so a replay session can
/// reconstruct exactly what the controller decided on each tick.
#[derive(Debug, Clone)]
pub struct ControlFrame {
    pub timestamp_us: u64,
    pub steering_rad: f32,
    pub throttle: f32,
    pub target_speed: f32,
    pub current_speed: f32,
}

// ── Public Handle ──────────────────────────────────────────────────────────

pub struct McapRecorder {
    handle: Option<thread::JoinHandle<()>>,
}

impl McapRecorder {
    /// Spawns the background writer thread. Takes ownership of `rx` so the
    /// recorder's lifetime is tied to the channel — when the TelemetryBus
    /// drops its sender the recorder drains remaining events and exits cleanly.
    pub fn start(path: impl AsRef<Path>, rx: mpsc::Receiver<TelemetryEvent>) -> Result<Self> {
        let path = path.as_ref().to_owned();
        let file = File::create(&path)
            .with_context(|| format!("cannot create MCAP file: {}", path.display()))?;
        let writer = BufWriter::new(file);
        let path_str = path.display().to_string();

        let handle = thread::Builder::new()
            .name("mcap-recorder".into())
            .spawn(move || mcap_loop(writer, rx, path_str))
            .context("failed to spawn mcap-recorder thread")?;

        info!(path = %path.display(), "mcap-recorder: started");
        Ok(Self {
            handle: Some(handle),
        })
    }

    /// Block until the background thread has flushed and closed the file.
    /// Call this during shutdown rather than relying on Drop so you know the
    /// file is complete before the process exits.
    pub fn finish(mut self) {
        info!("mcap-recorder: waiting for thread to flush");
        if let Some(h) = self.handle.take() {
            match h.join() {
                Ok(()) => info!("mcap-recorder: thread exited cleanly"),
                Err(e) => warn!("mcap-recorder: thread panicked: {:?}", e),
            }
        }
    }
}

impl Drop for McapRecorder {
    fn drop(&mut self) {
        // finish() is the clean path. If we reach Drop without it (e.g. on
        // early error return), join anyway to avoid leaving a partially-written
        // file with no footer — mcap::Writer::finish() writes the summary
        // section that makes the file seekable in Foxglove Studio.
        if let Some(h) = self.handle.take() {
            warn!("mcap-recorder: dropped without finish() — joining thread");
            let _ = h.join();
        }
    }
}

// ── Background Thread ──────────────────────────────────────────────────────

fn mcap_loop(mut file_writer: BufWriter<File>, rx: mpsc::Receiver<TelemetryEvent>, path: String) {
    info!(path = %path, "mcap-recorder: background thread started");

    let mut writer = Writer::new(&mut file_writer).expect("failed to init mcap writer");

    // The FileDescriptorSet lets Foxglove Studio decode our Protobuf messages
    // without needing the .proto files at runtime. Generated by build.rs.
    let descriptor_bytes = include_bytes!(concat!(env!("OUT_DIR"), "/messages_descriptor.bin"));

    // Register all channels up front so the MCAP header lists them before any
    // messages arrive — Foxglove Studio needs the schema before it can display
    // a topic in the panel selector.
    let mut register = |id: u16, topic: &str, message_name: &str| -> u16 {
        use std::sync::Arc;
        let schema = Arc::new(mcap::Schema {
            id,
            name: message_name.to_string(),
            encoding: "protobuf".to_string(),
            data: descriptor_bytes.to_vec().into(),
        });
        writer
            .add_channel(schema.id, topic, "protobuf", &Default::default())
            .expect("failed to add channel")
    };

    let ch_imu = register(0, "/imu", "car_software.ImuSample");
    let ch_lidar = register(1, "/lidar", "foxglove.PointCloud");
    let ch_sonar = register(2, "/sonar", "car_software.SonarFrame");
    let ch_metrics = register(3, "/metrics", "car_software.TickMetrics");
    let ch_control = register(4, "/control", "car_software.ControlFrame");

    let mut frames = 0u64;
    let mut last_log = Instant::now();

    // The loop exits naturally when the TelemetryBus drops all senders,
    // which happens when control_loop::run() returns and the bus is dropped.
    for event in &rx {
        let (id, ts_us, payload) = match &event {
            TelemetryEvent::Sensor(tf) => match &tf.frame {
                crate::hal::SensorFrame::Imu(s) => {
                    let pb = pb_car::ImuSample {
                        timestamp_us: tf.ts_us,
                        ax: s.ax,
                        ay: s.ay,
                        az: s.az,
                        gx: s.gx,
                        gy: s.gy,
                        gz: s.gz,
                    };
                    (ch_imu, tf.ts_us, pb.encode_to_vec())
                }
                crate::hal::SensorFrame::Lidar(cloud) => {
                    let point_stride = 16u32;
                    let mut data = Vec::with_capacity(cloud.points.len() * point_stride as usize);
                    // Pack as raw little-endian floats rather than protobuf repeated fields
                    // so Foxglove Studio's 3D panel can interpret the bytes directly as
                    // a GPU-ready vertex buffer without an extra decode step.
                    for p in &cloud.points {
                        data.extend_from_slice(&p.x.to_le_bytes());
                        data.extend_from_slice(&p.y.to_le_bytes());
                        data.extend_from_slice(&p.dist_m.to_le_bytes());
                        data.extend_from_slice(&p.angle_rad.to_le_bytes());
                    }
                    let pb = pb_fg::PointCloud {
                        timestamp: tf.ts_us,
                        frame_id: "lidar".into(),
                        point_stride,
                        fields: vec![
                            pb_fg::PackedElementField {
                                name: "x".into(),
                                offset: 0,
                                r#type: 7,
                            },
                            pb_fg::PackedElementField {
                                name: "y".into(),
                                offset: 4,
                                r#type: 7,
                            },
                            pb_fg::PackedElementField {
                                name: "distance".into(),
                                offset: 8,
                                r#type: 7,
                            },
                            pb_fg::PackedElementField {
                                name: "angle".into(),
                                offset: 12,
                                r#type: 7,
                            },
                        ],
                        data,
                    };
                    (ch_lidar, tf.ts_us, pb.encode_to_vec())
                }
                crate::hal::SensorFrame::Sonar { front, left, right } => {
                    let pb = pb_car::SonarFrame {
                        timestamp_us: tf.ts_us,
                        front_m: *front,
                        left_m: *left,
                        right_m: *right,
                    };
                    (ch_sonar, tf.ts_us, pb.encode_to_vec())
                }
            },

            TelemetryEvent::Metrics(m) => {
                let pb = pb_car::TickMetrics {
                    tick: m.tick,
                    timestamp_us: m.timestamp_us,
                    loop_us: m.loop_us as u64,
                    lateral_error_m: m.lateral_error_m,
                    heading_error_rad: m.heading_error_rad,
                    steering_rad: m.steering_rad,
                    throttle: m.throttle,
                    target_speed_ms: m.target_speed_ms,
                    current_speed_ms: m.current_speed_ms,
                    nearest_obstacle_m: m.nearest_obstacle_m,
                    gz_rad_s: m.gz_rad_s,
                    vy_ms: m.vy_ms,
                    estop: m.estop,
                    watchdog_miss: m.watchdog_miss,
                };
                (ch_metrics, m.timestamp_us, pb.encode_to_vec())
            }

            TelemetryEvent::Control(c) => {
                let pb = pb_car::ControlFrame {
                    timestamp_us: c.timestamp_us,
                    steering_rad: c.steering_rad,
                    throttle: c.throttle,
                    target_speed: c.target_speed,
                    current_speed: c.current_speed,
                };
                (ch_control, c.timestamp_us, pb.encode_to_vec())
            }
        };

        // MCAP timestamps are nanoseconds; our embedded timestamps are microseconds.
        let ts_ns = ts_us * 1_000;
        writer
            .write_to_known_channel(
                &MessageHeader {
                    channel_id: id,
                    sequence: 0,
                    log_time: ts_ns,
                    publish_time: ts_ns,
                },
                &payload,
            )
            .unwrap_or_else(|_| warn!("mcap-recorder: write error — disk full?"));

        frames += 1;

        if last_log.elapsed().as_secs() >= 5 {
            info!(frames, path = %path, "mcap-recorder: progress");
            last_log = Instant::now();
        }
    }

    // finish() writes the MCAP summary and index sections. Without it the file
    // is technically valid but Foxglove Studio cannot seek or display a timeline.
    writer.finish().expect("failed to cleanly finish mcap file");
    info!(path = %path, frames, "mcap-recorder: session complete");
}
