/// replay/recorder.rs — MCAP session recorder
///
/// Writes sensor frames and control metrics to an MCAP file that Foxglove
/// Studio opens natively. This version utilizes zero-copy binary Protobuf
/// serialization for maximum performance.
///
/// Channel layout
/// ──────────────
///   /imu          car_software.ImuSample       (Protobuf, 500 Hz)
///   /lidar        foxglove.PointCloud          (Protobuf, ~10 Hz)
///   /sonar        car_software.SonarFrame      (Protobuf, ~33 Hz)
///   /metrics      car_software.TickMetrics     (Protobuf, 100 Hz)
///   /control      car_software.ControlFrame    (Protobuf, 100 Hz)
///
/// Foxglove panel suggestions
/// ──────────────────────────
///   3D panel     → /lidar (Will auto-detect foxglove.PointCloud)
///   Plot panel   → /metrics.lateral_error_m, /control.steering_rad, etc.
///   Raw messages → /imu, /sonar
use std::{fs::File, io::BufWriter, path::Path, sync::mpsc, sync::Arc, thread, time::Instant};

use anyhow::{Context, Result};
use tracing::{debug, info, warn};

use mcap::{records::MessageHeader, Channel, Schema, Writer};
use prost::Message; // Required for .encode_to_vec()

use crate::hal::TimestampedFrame;
use crate::metrics::TickMetrics;

// ── Generated Protobuf Modules ─────────────────────────────────────────────
// Depending on how prost-build is configured, it groups generated files
// by their protobuf `package` name.
pub mod pb_fg {
    include!(concat!(env!("OUT_DIR"), "/foxglove.rs"));
}
pub mod pb_car {
    include!(concat!(env!("OUT_DIR"), "/car_software.rs"));
}

// ── Public Types ───────────────────────────────────────────────────────────

/// Sent from the control loop each tick alongside the sensor frame
#[derive(Debug, Clone)]
pub struct ControlFrame {
    pub timestamp_us: u64,
    pub steering_rad: f32,
    pub throttle: f32,
    pub target_speed: f32,
    pub current_speed: f32,
}

/// Everything the recorder thread needs per tick
#[derive(Debug, Clone)]
pub enum McapMessage {
    Sensor(TimestampedFrame),
    Metrics(Box<TickMetrics>),
    Control(ControlFrame),
}

// ── Public Handle ──────────────────────────────────────────────────────────

pub struct McapRecorder {
    tx: Option<mpsc::SyncSender<McapMessage>>,
    handle: Option<thread::JoinHandle<()>>,
}

impl McapRecorder {
    pub fn start(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref().to_owned();
        let file = File::create(&path)
            .with_context(|| format!("cannot create MCAP file: {}", path.display()))?;
        let writer = BufWriter::new(file);

        let (tx, rx) = mpsc::sync_channel::<McapMessage>(2048);
        let path_str = path.display().to_string();

        let handle = thread::Builder::new()
            .name("mcap-recorder".into())
            .spawn(move || mcap_loop(writer, rx, path_str))
            .context("failed to spawn mcap-recorder thread")?;

        info!(path = %path.display(), "mcap-recorder: started");
        Ok(Self {
            tx: Some(tx),
            handle: Some(handle),
        })
    }

    pub fn sender(&self) -> mpsc::SyncSender<McapMessage> {
        self.tx.as_ref().unwrap().clone()
    }

    pub fn finish(mut self) {
        let tx = self.tx.take();
        info!("mcap-recorder: closing channel");
        drop(tx);
        if let Some(h) = self.handle.take() {
            match h.join() {
                Ok(()) => info!("mcap-recorder: thread exited cleanly"),
                Err(e) => warn!("mcap-recorder: thread panicked: {:?}", e),
            }
        }
    }
}

impl Drop for McapRecorder {
    fn drop(&mut self) {
        if self.tx.is_some() {
            warn!("mcap-recorder: Drop without finish() — draining");
        }
        self.tx.take();
        if let Some(h) = self.handle.take() {
            let _ = h.join();
        }
    }
}

// ── Background Thread ──────────────────────────────────────────────────────

fn mcap_loop(mut file_writer: BufWriter<File>, rx: mpsc::Receiver<McapMessage>, path: String) {
    info!(path = %path, "mcap-recorder: background thread started");

    let mut writer = Writer::new(&mut file_writer).expect("failed to init mcap writer");

    // Load the FileDescriptorSet generated by build.rs so Foxglove can parse it
    let descriptor_bytes = include_bytes!(concat!(env!("OUT_DIR"), "/messages_descriptor.bin"));

    // Helper closure to register channels easily
    let mut register = |topic: &str, message_name: &str| -> Arc<Channel> {
        let schema = Arc::new(Schema {
            name: message_name.to_string(),
            encoding: "protobuf".to_string(),
            data: descriptor_bytes.to_vec(),
        });

        writer
            .add_channel(&Channel {
                topic: topic.to_string(),
                schema: Some(schema),
                message_encoding: "protobuf".to_string(),
                metadata: Default::default(),
            })
            .expect("failed to add channel")
    };

    // Register all channels with their fully qualified protobuf names
    let ch_imu = register("/imu", "car_software.ImuSample");
    let ch_lidar = register("/lidar", "foxglove.PointCloud");
    let ch_sonar = register("/sonar", "car_software.SonarFrame");
    let ch_metrics = register("/metrics", "car_software.TickMetrics");
    let ch_control = register("/control", "car_software.ControlFrame");

    let mut frames = 0u64;
    let mut last_log = Instant::now();

    for msg in &rx {
        let (channel, ts_us, payload) = match &msg {
            McapMessage::Sensor(tf) => match &tf.frame {
                crate::hal::SensorFrame::Imu(s) => {
                    let pb_msg = pb_car::ImuSample {
                        timestamp_us: tf.ts_us,
                        ax: s.ax,
                        ay: s.ay,
                        az: s.az,
                        gx: s.gx,
                        gy: s.gy,
                        gz: s.gz,
                    };
                    (ch_imu.clone(), tf.ts_us, pb_msg.encode_to_vec())
                }
                crate::hal::SensorFrame::Lidar(cloud) => {
                    let point_stride = 16; // 4 f32s * 4 bytes each

                    // Pre-allocate the exact byte size needed
                    let mut data = Vec::with_capacity(cloud.points.len() * point_stride as usize);

                    // Zero-copy binary serialization
                    for p in &cloud.points {
                        data.extend_from_slice(&p.x.to_le_bytes());
                        data.extend_from_slice(&p.y.to_le_bytes());
                        data.extend_from_slice(&p.dist_m.to_le_bytes());
                        data.extend_from_slice(&p.angle_rad.to_le_bytes());
                    }

                    let pb_msg = pb_fg::PointCloud {
                        timestamp: tf.ts_us,
                        frame_id: "lidar".into(),
                        point_stride,
                        fields: vec![
                            pb_fg::PackedElementField {
                                name: "x".into(),
                                offset: 0,
                                r#type: 7,
                            }, // 7 = FLOAT32
                            pb_fg::PackedElementField {
                                name: "y".into(),
                                offset: 4,
                                r#type: 7,
                            },
                            pb_fg::PackedElementField {
                                name: "distance".into(),
                                offset: 8,
                                r#type: 7,
                            },
                            pb_fg::PackedElementField {
                                name: "angle".into(),
                                offset: 12,
                                r#type: 7,
                            },
                        ],
                        data,
                    };
                    (ch_lidar.clone(), tf.ts_us, pb_msg.encode_to_vec())
                }
                crate::hal::SensorFrame::Sonar { front, left, right } => {
                    let pb_msg = pb_car::SonarFrame {
                        timestamp_us: tf.ts_us,
                        front_m: *front,
                        left_m: *left,
                        right_m: *right,
                    };
                    (ch_sonar.clone(), tf.ts_us, pb_msg.encode_to_vec())
                }
            },
            McapMessage::Metrics(m) => {
                let pb_msg = pb_car::TickMetrics {
                    tick: m.tick,
                    timestamp_us: m.timestamp_us,
                    loop_us: m.loop_us,
                    lateral_error_m: m.lateral_error_m,
                    heading_error_rad: m.heading_error_rad,
                    steering_rad: m.steering_rad,
                    throttle: m.throttle,
                    target_speed_ms: m.target_speed_ms,
                    current_speed_ms: m.current_speed_ms,
                    nearest_obstacle_m: m.nearest_obstacle_m,
                    gz_rad_s: m.gz_rad_s,
                    vy_ms: m.vy_ms,
                    estop: m.estop,
                    watchdog_miss: m.watchdog_miss,
                };
                (ch_metrics.clone(), m.timestamp_us, pb_msg.encode_to_vec())
            }
            McapMessage::Control(c) => {
                let pb_msg = pb_car::ControlFrame {
                    timestamp_us: c.timestamp_us,
                    steering_rad: c.steering_rad,
                    throttle: c.throttle,
                    target_speed: c.target_speed,
                    current_speed: c.current_speed,
                };
                (ch_control.clone(), c.timestamp_us, pb_msg.encode_to_vec())
            }
        };

        // Write to MCAP (MCAP timestamps are in nanoseconds)
        let ts_ns = ts_us * 1000;
        writer
            .write_to_known_channel(
                &MessageHeader {
                    channel_id: channel.id,
                    sequence: 0,
                    log_time: ts_ns as u64,
                    publish_time: ts_ns as u64,
                },
                &payload,
            )
            .unwrap_or_else(|_| warn!("mcap-recorder: write error — disk full?"));

        frames += 1;

        if last_log.elapsed().as_secs() >= 5 {
            info!(frames, path = %path, "mcap-recorder: progress");
            last_log = Instant::now();
        }
    }

    writer.finish().expect("failed to cleanly finish mcap file");
    info!(path = %path, frames, "mcap-recorder: session complete");
}
