/// stream/foxglove_bridge.rs — Foxglove WebSocket live bridge
///
/// Replaces the custom UDP streamer. Foxglove Studio connects directly to
/// ws://car.local:8765 (or the Pi's IP) via the standard
/// Foxglove WebSocket Protocol v1 — no custom `car-monitor` binary needed.
///
/// In Foxglove Studio:
///   1. Open connection → Foxglove WebSocket → ws://nfe.local:8765
///   2. Subscribe to topics: /imu  /lidar  /sonar  /metrics  /control
///
/// Channel layout
/// ──────────────
///   /imu          car_software.ImuSample       (Protobuf, ~500 Hz)
///   /lidar        foxglove.PointCloud          (Protobuf, ~10 Hz)
///   /sonar        car_software.SonarFrame      (Protobuf, ~33 Hz)
///   /metrics      car_software.TickMetrics     (Protobuf, 100 Hz)
///
/// Cargo.toml additions required
/// ──────────────────────────────
///   foxglove-ws = "0.3"      # Foxglove WebSocket server
///   prost = "0.12"           # For Protobuf binary encoding
use std::sync::Arc;
use tracing::{info, warn};

use crate::state::SharedState;

// ── Generated Protobuf Modules ─────────────────────────────────────────────
#[cfg(feature = "foxglove-ws")]
pub mod pb_fg {
    include!(concat!(env!("OUT_DIR"), "/foxglove.rs"));
}
#[cfg(feature = "foxglove-ws")]
pub mod pb_car {
    include!(concat!(env!("OUT_DIR"), "/car_software.rs"));
}

/// Optional live-bridge handle. Dropping it shuts down the WebSocket server.
pub struct FoxgloveBridge {
    _inner: BridgeInner,
}

pub const DEFAULT_PORT: u16 = 8765;

impl FoxgloveBridge {
    /// Bind to `0.0.0.0:port` and start broadcasting sensor snapshots.
    pub fn start(
        state: Arc<SharedState>,
        port: u16,
        push_interval_ms: u64,
    ) -> Result<Self, anyhow::Error> {
        #[cfg(feature = "foxglove-ws")]
        {
            use foxglove_ws::{Server, ServerOptions};
            // Note: Depending on your exact `foxglove-ws` crate version, you might
            // need to import `ChannelBuilder` or use `foxglove_ws::Channel`.
            use prost::Message;
            use std::{thread, time::Duration};

            let server = Server::bind(
                format!("0.0.0.0:{port}"),
                ServerOptions::default().name("NFE car"),
            )?;

            // Load the Protobuf Descriptor blob generated by build.rs
            let descriptor_bytes =
                include_bytes!(concat!(env!("OUT_DIR"), "/messages_descriptor.bin"));

            // Helper closure to register Protobuf channels for the WebSocket
            let mut register = |topic: &str, message_name: &str| {
                // foxglove-ws v0.3 typically requires explicitly defining the schema name
                // so it knows which message to pull from the descriptor bytes.
                server.add_channel(foxglove_ws::Channel::new(
                    topic,
                    "protobuf",   // message encoding
                    message_name, // schema name
                    "protobuf",   // schema encoding
                    descriptor_bytes.to_vec(),
                ))
            };

            let ch_imu = register("/imu", "car_software.ImuSample")?;
            let ch_lidar = register("/lidar", "foxglove.PointCloud")?;
            let ch_sonar = register("/sonar", "car_software.SonarFrame")?;

            // If you add metrics to the snapshot later, register it here!
            // let ch_metrics = register("/metrics", "car_software.TickMetrics")?;

            let state2 = state.clone();

            thread::Builder::new()
                .name("foxglove-bridge".into())
                .spawn(move || {
                    let interval = Duration::from_millis(push_interval_ms);
                    loop {
                        thread::sleep(interval);
                        if state2.is_shutdown() {
                            break;
                        }

                        let snap = state2.snapshot();
                        let ts_ns = snap.lidar.timestamp_us * 1_000;

                        // 1. IMU Binary Serialization
                        let imu_msg = pb_car::ImuSample {
                            timestamp_us: snap.imu.timestamp_us,
                            ax: snap.imu.ax,
                            ay: snap.imu.ay,
                            az: snap.imu.az,
                            gx: snap.imu.gx,
                            gy: snap.imu.gy,
                            gz: snap.imu.gz,
                        };
                        let _ = server.publish(ch_imu, ts_ns, &imu_msg.encode_to_vec());

                        // 2. LiDAR Zero-Copy Packed Bytes Serialization
                        let point_stride = 16;
                        let mut lidar_data =
                            Vec::with_capacity(snap.lidar.points.len() * point_stride as usize);

                        for p in &snap.lidar.points {
                            lidar_data.extend_from_slice(&p.x.to_le_bytes());
                            lidar_data.extend_from_slice(&p.y.to_le_bytes());
                            lidar_data.extend_from_slice(&p.dist_m.to_le_bytes());
                            lidar_data.extend_from_slice(&p.angle_rad.to_le_bytes());
                        }

                        let lidar_msg = pb_fg::PointCloud {
                            timestamp: snap.lidar.timestamp_us,
                            frame_id: "lidar".into(),
                            point_stride,
                            fields: vec![
                                pb_fg::PackedElementField {
                                    name: "x".into(),
                                    offset: 0,
                                    r#type: 7,
                                },
                                pb_fg::PackedElementField {
                                    name: "y".into(),
                                    offset: 4,
                                    r#type: 7,
                                },
                                pb_fg::PackedElementField {
                                    name: "distance".into(),
                                    offset: 8,
                                    r#type: 7,
                                },
                                pb_fg::PackedElementField {
                                    name: "angle".into(),
                                    offset: 12,
                                    r#type: 7,
                                },
                            ],
                            data: lidar_data,
                        };
                        let _ = server.publish(ch_lidar, ts_ns, &lidar_msg.encode_to_vec());

                        // 3. Sonar Binary Serialization
                        let sonar_msg = pb_car::SonarFrame {
                            timestamp_us: snap.lidar.timestamp_us, // Or wherever sonar TS is stored
                            front_m: snap.sonar_m[0],
                            left_m: snap.sonar_m[1],
                            right_m: snap.sonar_m[2],
                        };
                        let _ = server.publish(ch_sonar, ts_ns, &sonar_msg.encode_to_vec());
                    }
                    info!("foxglove-bridge: thread exiting");
                })
                .expect("failed to spawn foxglove-bridge thread");

            info!("foxglove-bridge: listening on ws://0.0.0.0:{port}");
            info!("foxglove-bridge: connect in Foxglove Studio → Open connection → Foxglove WebSocket → ws://<pi-ip>:{port}");

            Ok(Self {
                _inner: BridgeInner::Live(server),
            })
        }

        #[cfg(not(feature = "foxglove-ws"))]
        {
            let _ = (state, push_interval_ms);
            warn!(
                "foxglove-bridge: foxglove-ws feature not enabled — live streaming unavailable.\n\
                 Add `foxglove-ws = \"0.3\"` to Cargo.toml and build with --features foxglove-ws"
            );
            Ok(Self {
                _inner: BridgeInner::Disabled,
            })
        }
    }
}

// ── Internal discriminant ──────────────────────────────────────────────────

enum BridgeInner {
    #[cfg(feature = "foxglove-ws")]
    Live(Arc<foxglove_ws::Server>), // foxglove-ws usually returns Arc<Server> or Server handle
    Disabled,
}
